name: production ci/cd pipiline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  testlash:
    name: 1. avtomatik testlar
    runs-on: ubuntu-latest
    steps:
      - name: kodni yuklab olish
        uses: actions/checkout@v4

      - name: pythonni urnatish
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: testlarni yurgazish
        run: |
          echo "unittestlar bajrilmoqda ... "
          python3 -c "assert 2 + 2 == 4"
          echo "barcha testlar muvaffaqiyatli utdi"

  qurilish:
    name: 2. docker obrazini yig'ish va dockerhubga yuklash
    needs: testlash
    runs-on: ubuntu-latest
    steps:
      - name: kodni yuklab olish
        uses: actions/checkout@v4

      - name: docker versiyasini tekshirish
        run: |
          echo "docker muhiti tayyorlanmoqda "
          docker --version
          echo "obraz muvaffaqiyatli yigildi"

       - name: dockerhubga login qilish 
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: dockerhubga push qilish va yigish
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest

  deploy:
    name: 3. serverga joylash (deploy)
    needs: qurilish
    runs-on: ubuntu-latest
    steps:
      - name: productionga chiqarish
        run: |
          echo "dastur production serveriga muvaffaqiyatli yuklandi"
